# Generated by Axiom CLI — do not delete (path fixup kept below).
# Ensures pytest can resolve "from nodes.<module> import <func>" imports
# whether tests are run from the package root or inside the Docker build.
import sys, os as _os
sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))

import pytest
import trimesh

from gen.axiom_context import SecretStatus


class AxTestContext:
    """Minimal AxiomContext implementation for unit tests. Shared across all
    node test files via the `ax` fixture below."""

    class _Logger:
        def debug(self, msg: str, **attrs) -> None: pass
        def info(self, msg: str, **attrs) -> None: pass
        def warn(self, msg: str, **attrs) -> None: pass
        def error(self, msg: str, **attrs) -> None: pass

    class _Secrets:
        def __init__(self, m: dict, revoked: set) -> None:
            self._m = m or {}
            self._revoked = revoked or set()

        def get(self, name: str):
            v = self._m.get(name)
            return (v, True) if v is not None else ("", False)

        def status(self, name: str) -> SecretStatus:
            if name in self._m:
                return SecretStatus.AVAILABLE
            if name in self._revoked:
                return SecretStatus.REVOKED
            return SecretStatus.UNSET

    def __init__(self, secrets_map: dict | None = None, revoked_names: set | None = None) -> None:
        self.log = self._Logger()
        self.secrets = self._Secrets(secrets_map or {}, revoked_names)
        self.execution_id = "test-execution-id"
        self.flow_id = "test-flow-id"
        self.tenant_id = "test-tenant-id"


@pytest.fixture
def ax():
    return AxTestContext()


# --- Known-geometry fixtures -------------------------------------------------
# A unit cube centered at the origin is the oracle: hand-computable volume=1,
# surface area=6, center of mass=(0,0,0), inertia diag=1/6, Euler number=2,
# body_count=1, watertight=True, hull==itself, AABB==OBB==itself.


@pytest.fixture
def unit_cube():
    return trimesh.creation.box(extents=[1, 1, 1])


@pytest.fixture
def unit_cube_stl(unit_cube):
    return unit_cube.export(file_type="stl")


@pytest.fixture
def unit_cube_obj(unit_cube):
    data = unit_cube.export(file_type="obj")
    return data.encode("utf-8") if isinstance(data, str) else data


@pytest.fixture
def offset_cube_stl():
    """A unit cube translated +0.5 along x — overlaps `unit_cube` by exactly
    half its volume (0.5 x 1 x 1), giving hand-computable boolean oracles:
    union=1.5, intersection=0.5, difference=0.5."""
    b = trimesh.creation.box(extents=[1, 1, 1])
    b.apply_translation([0.5, 0, 0])
    return b.export(file_type="stl")


@pytest.fixture
def sphere_stl():
    return trimesh.creation.icosphere(subdivisions=3).export(file_type="stl")


@pytest.fixture
def sphere_face_count():
    return len(trimesh.creation.icosphere(subdivisions=3).faces)


@pytest.fixture
def inconsistent_winding_stl(unit_cube):
    """A cube with exactly one face's winding reversed — is_winding_consistent
    is False until FixNormals repairs it."""
    m = unit_cube.copy()
    m.faces[0] = m.faces[0][::-1]
    return m.export(file_type="stl")


@pytest.fixture
def holey_cube_stl(unit_cube):
    """A cube missing one triangular face — not watertight until FillHoles
    closes the resulting square hole (which reconstructs exactly the missing
    quad, restoring the original 8 vertices / volume 1.0)."""
    m = unit_cube.copy()
    m.faces = m.faces[1:]
    m.remove_unreferenced_vertices()
    return m.export(file_type="stl")
